#ifndef __CONST_H
# define __CONST_H

# define TINYIRC_DEFPORT 6667
# define TINYIRC_DEFADDR INADDR_ANY
# define TINYIRC_DEFBACKLOG  32
# define TINYIRC_MSG_LEN 512
# define TINYIRC_MSG_SEP "\r\n"
# define TINYIRC_NICKLEN 9
# define TINYIRC_CHANNAMELEN 50

#endif
