#ifndef __CONST_H
# define __CONST_H

# define TINYIRC_DEFPORT 6667
# define TINYIRC_DEFADDR INADDR_ANY
# define TINYIRC_DEFBACKLOG  32
# define TINYIRC_MSG_LEN 512
# define TINYIRC_MSG_SEP "\r\n"
# define TINYIRC_NICKLEN 9
# define TINYIRC_CHANNAMELEN 50

typedef enum    e_resp_code
{
    RPL_TOPIC = 332,

    ERR_NOSUCHNICK = 401,
    ERR_NOSUCHCHANNEL = 403,
    ERR_TOOMANYCHANNELS = 405,
    ERR_NORECIPIENT = 411,
    ERR_NOTEXTTOSEND = 412,
    ERR_UNKNOWNCOMMAND = 421,
    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,
    ERR_NICKCOLLISION = 436,
    ERR_UNAVAILRESOURCE = 437,
    ERR_NOTONCHANNEL = 442,
    ERR_NOTREGISTERED = 451,
    ERR_NEEDMOREPARAMS = 461,
    ERR_ALREADYREGISTRED = 462,
    ERR_CHANNELISFULL = 471,
    ERR_INVITEONLYCHAN = 473,
    ERR_BANNEDFROMCHAN = 474,
    ERR_BADCHANNELKEY = 475,
    ERR_BADCHANMASK = 476,
    ERR_RESTRICTED = 484,
}               t_resp_code;

#endif
